import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#ffff",
  },
  backgroundContainer: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    height: 650,
  },
  viewWeather: {
    flex: 2,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 100,
  },
  h1: {
    color: "white",
    fontSize: 30,
    fontWeight: "regular",
    fontFamily: "RobotoCondensed_400Regular",
    marginBottom: 30,
    textShadowColor: "rgba(0, 0, 0, 0.55)",
    textShadowOffset: { width: -1, height: 1 },
    textShadowRadius: 10,
  },
  newContent: {
    flex: 2,
    justifyContent: "center",
    alignItems: "center",
  },
  label: {
    color: "#6e6e6e",
    fontSize: 15,
    paddingBottom: 5,
  },
  buttonPressable: {
    justifyContent: "center",
    alignItems: "center",
    height: 40,
    width: 70,
    marginTop: 30,
    elevation: 5,
    borderRadius: 3,
    backgroundColor: "white",
    borderColor: "gray",
    borderWidth: 0.3,
  },
  viewButton: {
    justifyContent: "center",
    alignItems: "center",
  },
  dropdown: {
    backgroundColor: "white",
    color: "grey",
    fontSize: 14,
    paddingLeft: 15,
    paddingRight: 15,
    height: 45,
    width: 250,
    borderColor: "gray",
    borderWidth: 0.5,
    borderRadius: 8,
    paddingHorizontal: 8,
    marginRight: 5,
    marginBottom: 10,
  },
  inputSearchStyle: {
    height: 40,
    fontSize: 16,
  },
  dropdownUF: {
    backgroundColor: "white",
    color: "grey",
    fontSize: 14,
    paddingLeft: 15,
    paddingRight: 15,
    height: 45,
    width: 80,
    borderColor: "gray",
    borderWidth: 0.5,
    borderRadius: 8,
    paddingHorizontal: 8,
    marginRight: 5,
    marginBottom: 10,
  },
  dropdownContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
});
